### ISSUE TITLE
unused requirements

### ISSUE THREAD

**Issue by pavelgrib** [IBM/AIF360#112]
Why are there a bunch of packages in this repo that are not used anywhere in the codebase?  Specifically:
Orange3
scs
networkx

Furthermore, there are packages only used in the notebooks and not in the library:
all the ipython stuff
lime
tqdm
matplotlib

**Comment by hoffmansc** [comment]
Orange3, scs, and networkx were added to the requirements file because they're dependencies for other packages used by the toolbox. We previously noticed installation issues with different versions of these so we specified them here. It looks like Orange3 is no longer a required dependency for BlackBoxAuditing though so we can probably remove that.

As for the notebook dependencies, I'd like to keep them in the same file. This makes it easier to install everything in one go and make use of everything in the repository.
