### ISSUE TITLE
Raw Probabilities for adversarial debiasing

### ISSUE THREAD

**Issue by Drew2019** [IBM/AIF360#144]
Is there a way to retrieve the raw predicted probabilities (not labels, but probabilities that someone falls within a class)?

**Comment by krvarshney** [comment]
The StructuredDataset class has a _scores_ field which gets populated by many models. See https://aif360.readthedocs.io/en/latest/modules/datasets.html#structured-dataset for more details.

**Comment by AndrewBoyd10** [comment]
I'm still not seeing a way to do this, and I'd be quite thankful for guidance for adversarial debiasing specifically. For example, if I run the following, all I get is a 0/1 label instead of probabilities. 

dataset_nodebiasing_test = plain_model.predict (dataset_orig_test)
scores = dataset_nodebiasing_test.scores
scores = pd.DataFrame (scores)
scores

**Comment by Drew2019** [comment]
I'm still not seeing a way to do this for adversarial debiasing specifically, and I'd be quite thankful for guidance. For example, if I run the following, all I get is a 0/1 labels instead of probabilities.

dataset_nodebiasing_test = plain_model.predict (dataset_orig_test)
scores = dataset_nodebiasing_test.scores
scores = pd.DataFrame (scores)
scores

**Comment by pronics2004** [comment]
It is possible that the scores are saturated to 0 or 1 during training, in general, `dataset_nodebiasing_test.scores` should return non-thresholded scores.
